##name: Test SSH Connection

#on:
 #workflow_dispatch:

#jobs:
 #test-ssh:
  #runs-on: self-hosted

  #steps:
  #- name: Show server information
    #run: |
      #echo "Runner ejecutándose en el servidor"
      #hostname 
      #whoami
      #pwd 
      #php -v 
      #nginx -v




name: Deploy to local server

on:
 pull_request:
  branches:
  - main
  types:
  - closed

jobs:
 deploy:
  if: github.event.pull_request.merged == true
  runs-on: self-hosted


  steps:
  - name: Deploy application
    run: |
      cd /var/www/Catalogo_de_productos
      git fetch origin
      git reset --hard origin/main
      composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
      php spark cache:clear
