name: Test SSH Connection

on:
 workflow_dispatch:

jobs:
 test-ssh:
  runs-on: self-hosted

  steps:
  - name: Show server information
    run: |
      echo "Runner ejecutándose en el servidor"
      hostname 
      whoami
      pwd 
      php -v 
      nginx -v